language: go
services:
  - docker
go:
  - "1.13.x"
  - "1.14.x"
script:
  - export GO111MODULE=on
  - GOOS=linux go build ./azqueue
  - GOOS=darwin go build ./azqueue
  - GOOS=windows go build ./azqueue
  - docker run -d -p 10000:10000 -p 10001:10001 mcr.microsoft.com/azure-storage/azurite
  - go test -race -short -cover -v ./azqueue
