language: go
services:
  - docker
go:
  - "1.13.x"
  - "1.14.x"
env:
  - DOCKER_COMPOSE_VERSION=1.26.2
before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
script:
  - export GO111MODULE=on
  - GOOS=linux go build ./azqueue
  - GOOS=darwin go build ./azqueue
  - GOOS=windows go build ./azqueue
  - docker-compose up -d
  - go test -race -short -cover -v ./azqueue
